server:
  port: 8080

spring:
  application:
    name: portal-server
  profiles:
    include: db, exception
    group:
      test: debug
      local: debug
      alpha: debug
      real:
    active: local
